In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [2]:
iris = load_iris()

In [3]:
X = iris.data

In [4]:
y = iris.target.reshape(-1, 1)

In [5]:
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y)

E:\Anaconda\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [8]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [9]:
input_size = X.shape[1]
hidden_size = 10
output_size = y.shape[1]

In [10]:
np.random.seed(42)
weights_input_hidden = np.random.randn(input_size, hidden_size)
biases_hidden = np.random.rand(1, hidden_size)
weights_hidden_output = np.random.randn(hidden_size, output_size)
biases_output = np.random.rand(1, output_size)

In [11]:
learning_rate = 0.1
epochs = 10

In [12]:
for epoch in range(epochs):
    hidden_layer_input = np.dot(X_train, weights_input_hidden) + biases_hidden
    hidden_layer_output = sigmoid(hidden_layer_input)
    
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + biases_output
    output = sigmoid(output_layer_input)
    print(output)
    
    error = y_train - output
    print(error)
    
    output_delta = error * sigmoid_derivative(output)
    
    hidden_error = output_delta.dot(weights_hidden_output.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)
    
    weights_hidden_output += hidden_layer_output.T.dot(output_delta) * learning_rate
    biases_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate
    weights_input_hidden += X_train.T.dot(hidden_delta) * learning_rate
    biases_hidden += np.sum(hidden_delta, axis=0, keepdims=True) * learning_rate

[[0.59466037 0.19125663 0.67783074]
 [0.52278367 0.16358238 0.65336486]
 [0.63940914 0.16137951 0.5328947 ]
 [0.58742432 0.18253156 0.67450744]
 [0.61660015 0.19270724 0.67380959]
 [0.73135756 0.17533033 0.43942431]
 [0.63920611 0.16623097 0.47819629]
 [0.5945575  0.19668475 0.71464832]
 [0.5807698  0.18684265 0.69010499]
 [0.53299273 0.16764131 0.66841324]
 [0.72745882 0.20055872 0.36651168]
 [0.65255435 0.18435124 0.41551056]
 [0.64365689 0.1624572  0.50517177]
 [0.57208296 0.18627465 0.67890605]
 [0.57820169 0.19276919 0.71361249]
 [0.69108794 0.17527733 0.58640713]
 [0.67342801 0.1739655  0.47761444]
 [0.68642359 0.19210336 0.40086929]
 [0.64942228 0.16278046 0.53143455]
 [0.69891522 0.1943068  0.32777782]
 [0.65756803 0.17502462 0.47799425]
 [0.6930819  0.17323467 0.4365482 ]
 [0.67992695 0.19288824 0.41295175]
 [0.59660895 0.19731155 0.71151371]
 [0.69971768 0.16806369 0.47542345]
 [0.64750667 0.16707573 0.56803625]
 [0.61454214 0.20933635 0.73302426]
 [0.60107216 0.19619387 0.69

In [13]:
hidden_layer_input = np.dot(X_test, weights_input_hidden) + biases_hidden
hidden_layer_output = sigmoid(hidden_layer_input)
output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + biases_output
predicted_output = sigmoid(output_layer_input)

In [14]:
predicted_classes = np.argmax(predicted_output, axis=1)
true_classes = np.argmax(y_test, axis=1)
print(true_classes)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [15]:
accuracy = np.mean(predicted_classes == true_classes)
print(f"Accuracy: {accuracy * 100}%")

Accuracy: 36.666666666666664%
